### ISSUE TITLE
Add comment, like, user_cleaerd_board 엔티티, 리포지토리 제작 필요

### ISSUE THREAD

**Issue by Garodden** [Garodden/keyboard-arena#12]
#  Todo 🗿
- [x] like 엔티티 만들기
- [x] like 리포지토리 만들기
- [x] comment 엔티티 만들기
- [x] comment 리포지토리 만들기
- [x] user_cleaerd_board 엔티티 만들기
- [x] user_cleaerd_board 리포지토리 만들기

**Comment by Garodden** [comment]
자자체 pk 없이 외래 키로만 존재하는 테이블에 대한 엔티티(Like, Cleared) 들을 위하여 복합 키인 UserBoardCompositeKey.java를 생성
