### ISSUE TITLE
Arena API 세부 수정 사항 TODO List

### ISSUE THREAD

**Issue by Garodden** [Garodden/keyboard-arena#34]
# Todo List 
- [x] 개별 아레나 페이지 들어갈 시 바로 시작 시간을 기록하지 않고, 팝업을 띄워서 아레나의 매케니즘에 대해 설명해준 다음, [확인] 버튼을 눌렀을때 시작하도록 한다.
- [ ] 아레나 참전시 포인트 트렌잭션 시스템 
    - 주간 아레나는 첫 클리어시 포인트 1000씩 지급
    - 아레나 클리어를 재시도 할 시 포인트를 100 지급해야 함.
    - 포인트가 없고 재시도할 의향이 없으면 post를 할 수 없도록 프론트에서 설정을 해줘야 한다.
    - 위에서 말했던 팝업에서 처음 시도하는 상황에는 바로 시도를 할 수 있게 해주고, 재시도 하는 상황에서는 포인트를 지불해야지만 아레나 참전 페이지로 넘어갈 수 있도록 해준다. 
    - 재시도 의향이 없다면 참전 불가능한 페이지로 보내주도록 한다.
- [x] 개별 아레나 UI에서 이때까지 깬 사람들의 등수도 보여주도록 구현을 해야한다.
- [ ]

**Comment by Garodden** [comment]
트랜젝션 시스템은 포기하기로 한다
