### ISSUE TITLE
Feat : Arena/ 아레나 기능 구현

### ISSUE THREAD

**Issue by Garodden** [Garodden/keyboard-arena#5]
#  Arena?
 데이터테이블에서 Arena 게시판을 가져와서 그 기능 구현

# todo
- [x] entity 구현
- [x] repository 구현
- [x] 전체 arena 조회 API 구현
- [x] 개별 arena 조회 API 구현
- [x] arena참전 API 구현
- [x] arena 생성 API 구현
- [x] arena 삭제 API 구현
