### ISSUE TITLE
Feat: 마이페이지 관련 UI 수정

### ISSUE THREAD

**Issue by biiit4894** [Garodden/keyboard-arena#50]
## TODO
- [ ] 마이페이지 홈 ui
- [ ] 마이페이지 내가 참전한 아레나 조회 ui 
- [ ] 마이페이지 내가 댓글 단 게시물 조회 ui
- [ ] 마이페이지 내가 쓴 게시물 조회 ui
- [ ] 마이페이지 비밀번호 변경 ui
- [ ] 마이페이지 회원 탈퇴 ui
