### ISSUE TITLE
Fix: LikeComment.js 아레나와 호환, delete 버튼 API와 연동

### ISSUE THREAD

**Issue by Garodden** [Garodden/keyboard-arena#52]
#Todo
- [x] LikeComment.js 아레나 API와 동시에 호환 가능하도록 하기
- [ ] like 버튼 비동기처리화
- [x] delete 버튼 API와 연동

**Comment by Garodden** [comment]
like 버튼 비동기처리도 포기하기로 한다
